// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_control`, `build_input`, `build_output`, `fill`, `new`, `new`, `open_playback_stream`, `open`, `pop_src_frame`, `process`, `push_playback_samples`, `recv_into`, `refill`, `spawn_capture_thread`, `spawn_playback_thread`, `spawn_remote_audio_playback`, `stop_capture_for_connection`, `write_packets`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AudioCaptureHandle`, `CaptureControl`, `LinearResampler`, `MicStream`, `PlaybackPump`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<List<AudioSourceDto>> listAudioSources() =>
    RustLib.instance.api.crateApiAudioListAudioSources();

Future<void> startAudioCapture({
  required String connectionId,
  String? sourceId,
}) => RustLib.instance.api.crateApiAudioStartAudioCapture(
  connectionId: connectionId,
  sourceId: sourceId,
);

Future<void> setAudioMuted({
  required String connectionId,
  required bool muted,
}) => RustLib.instance.api.crateApiAudioSetAudioMuted(
  connectionId: connectionId,
  muted: muted,
);

Future<void> setAudioSource({required String connectionId, String? sourceId}) =>
    RustLib.instance.api.crateApiAudioSetAudioSource(
      connectionId: connectionId,
      sourceId: sourceId,
    );

Future<void> stopAudioCapture({required String connectionId}) => RustLib
    .instance
    .api
    .crateApiAudioStopAudioCapture(connectionId: connectionId);

bool isAudioCaptureActive({required String connectionId}) => RustLib
    .instance
    .api
    .crateApiAudioIsAudioCaptureActive(connectionId: connectionId);

/// Returns false when no capture is active.
bool isAudioMuted({required String connectionId}) =>
    RustLib.instance.api.crateApiAudioIsAudioMuted(connectionId: connectionId);

class AudioSourceDto {
  final String id;
  final String name;
  final bool isDefault;

  const AudioSourceDto({
    required this.id,
    required this.name,
    required this.isDefault,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ isDefault.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioSourceDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          isDefault == other.isDefault;
}
