// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `stop_capture_for_connection`

Future<void> startDesktopAudioCapture({required String connectionId}) => RustLib
    .instance
    .api
    .crateApiDesktopAudioStartDesktopAudioCapture(connectionId: connectionId);

Future<void> stopDesktopAudioCapture({required String connectionId}) => RustLib
    .instance
    .api
    .crateApiDesktopAudioStopDesktopAudioCapture(connectionId: connectionId);

bool isDesktopAudioCaptureActive({required String connectionId}) =>
    RustLib.instance.api.crateApiDesktopAudioIsDesktopAudioCaptureActive(
      connectionId: connectionId,
    );
