// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `run_pipewire_capture`, `spawn_encode_thread`, `spawn_pipewire_thread`, `stop_capture_for_connection`, `to_stereo_interleaved`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DesktopAudioCaptureHandle`, `RawChunk`

Future<void> startDesktopAudioCapture({required String connectionId}) => RustLib
    .instance
    .api
    .crateApiDesktopAudioStartDesktopAudioCapture(connectionId: connectionId);

Future<void> stopDesktopAudioCapture({required String connectionId}) => RustLib
    .instance
    .api
    .crateApiDesktopAudioStopDesktopAudioCapture(connectionId: connectionId);

bool isDesktopAudioCaptureActive({required String connectionId}) =>
    RustLib.instance.api.crateApiDesktopAudioIsDesktopAudioCaptureActive(
      connectionId: connectionId,
    );
