// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cleanup_session_resources`, `clear_current_session`, `compare_offer_priority`, `compute_sha256`, `create_unique_destination_file`, `drain_states`, `fail_current_session`, `finalize_received_file`, `get_or_spawn_actor`, `handle_accept_offer`, `handle_cancel_transfer`, `handle_incoming_chunk`, `handle_incoming_eof`, `handle_incoming_message`, `handle_reject_offer`, `handle_send_offer`, `handle_sender_failed`, `handle_sender_finished`, `handle_sender_progress`, `handle_tick`, `new`, `now_nonce`, `parse_file_message`, `push_state`, `request_actor`, `run_actor`, `sanitize_file_name`, `should_coalesce_progress_state`, `spawn_background_task`, `spawn_sender_pipeline`, `split_file_name`, `state_snapshot_for_session`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ActorCommand`, `ActorHandle`, `FileTransferActor`, `FileTransferSession`, `IncomingFileMessage`, `OutMetadata`, `SessionRole`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<bool> isFileTransferControlMessage({required String text}) => RustLib
    .instance
    .api
    .crateApiFileTransferIsFileTransferControlMessage(text: text);

void initTransfer({required String connectionId}) => RustLib.instance.api
    .crateApiFileTransferInitTransfer(connectionId: connectionId);

Future<void> sendOffer({
  required String connectionId,
  required String filePath,
}) => RustLib.instance.api.crateApiFileTransferSendOffer(
  connectionId: connectionId,
  filePath: filePath,
);

Future<void> acceptOffer({
  required String connectionId,
  required String saveDir,
}) => RustLib.instance.api.crateApiFileTransferAcceptOffer(
  connectionId: connectionId,
  saveDir: saveDir,
);

Future<void> rejectOffer({required String connectionId, String? reason}) =>
    RustLib.instance.api.crateApiFileTransferRejectOffer(
      connectionId: connectionId,
      reason: reason,
    );

Future<void> cancelTransfer({required String connectionId, String? reason}) =>
    RustLib.instance.api.crateApiFileTransferCancelTransfer(
      connectionId: connectionId,
      reason: reason,
    );

Future<void> handleFileMessage({
  required String connectionId,
  required String text,
}) => RustLib.instance.api.crateApiFileTransferHandleFileMessage(
  connectionId: connectionId,
  text: text,
);

Future<void> handleFileChunk({
  required String connectionId,
  required List<int> bytes,
}) => RustLib.instance.api.crateApiFileTransferHandleFileChunk(
  connectionId: connectionId,
  bytes: bytes,
);

Future<void> tick({required String connectionId}) =>
    RustLib.instance.api.crateApiFileTransferTick(connectionId: connectionId);

Future<List<FileTransferStateDto>> drainStates({
  required String connectionId,
}) => RustLib.instance.api.crateApiFileTransferDrainStates(
  connectionId: connectionId,
);

Future<void> disposeTransfer({required String connectionId}) => RustLib
    .instance
    .api
    .crateApiFileTransferDisposeTransfer(connectionId: connectionId);

class FileTransferStateDto {
  final TransferStatusDto status;
  final String? fileName;
  final BigInt totalBytes;
  final BigInt bytesTransferred;
  final String? error;

  const FileTransferStateDto({
    required this.status,
    this.fileName,
    required this.totalBytes,
    required this.bytesTransferred,
    this.error,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      fileName.hashCode ^
      totalBytes.hashCode ^
      bytesTransferred.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileTransferStateDto &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          fileName == other.fileName &&
          totalBytes == other.totalBytes &&
          bytesTransferred == other.bytesTransferred &&
          error == other.error;
}

enum TransferStatusDto {
  idle,
  offering,
  offered,
  transferring,
  receiving,
  completed,
  error,
}
