// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clear_target`, `get_or_create`, `handle_input_message`, `parse_input_message`, `register_target`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ConnState`, `InputMsg`, `InputTarget`, `MouseButton`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

/// Host-side consent toggle. Must be explicitly enabled before any
/// `input_*` control message from the peer is acted on.
Future<void> setRemoteControlAllowed({
  required String connectionId,
  required bool allowed,
}) => RustLib.instance.api.crateApiInputInjectSetRemoteControlAllowed(
  connectionId: connectionId,
  allowed: allowed,
);
