// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `adapt_quality`, `clamped`, `ensure_encoder`, `find_monitor`, `find_window`, `fit_dimensions`, `new`, `process`, `resize_into`, `run_poll_loop`, `run_recorder_loop`, `spawn_capture_thread`, `spawn_encode_thread`, `start_video_recorder`, `step_tier`, `write_outputs`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CaptureHandle`, `EncodeOutput`, `EncodePipeline`, `QualityTier`, `RawFrame`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

List<CaptureSourceDto> listCaptureSources() =>
    RustLib.instance.api.crateApiScreenCaptureListCaptureSources();

Future<void> startCapture({
  required String connectionId,
  required String sourceId,
  required CaptureConfigDto config,
  required bool localPreview,
}) => RustLib.instance.api.crateApiScreenCaptureStartCapture(
  connectionId: connectionId,
  sourceId: sourceId,
  config: config,
  localPreview: localPreview,
);

Future<void> stopCapture({required String connectionId}) => RustLib.instance.api
    .crateApiScreenCaptureStopCapture(connectionId: connectionId);

bool isCaptureActive({required String connectionId}) => RustLib.instance.api
    .crateApiScreenCaptureIsCaptureActive(connectionId: connectionId);

class CaptureConfigDto {
  final int fps;
  final int targetBitrateKbps;

  const CaptureConfigDto({required this.fps, required this.targetBitrateKbps});

  @override
  int get hashCode => fps.hashCode ^ targetBitrateKbps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CaptureConfigDto &&
          runtimeType == other.runtimeType &&
          fps == other.fps &&
          targetBitrateKbps == other.targetBitrateKbps;
}

class CaptureSourceDto {
  final String id;
  final String name;
  final String kind;
  final int width;
  final int height;

  const CaptureSourceDto({
    required this.id,
    required this.name,
    required this.kind,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      kind.hashCode ^
      width.hashCode ^
      height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CaptureSourceDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          kind == other.kind &&
          width == other.width &&
          height == other.height;
}
