// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

void initScreenCapture() =>
    RustLib.instance.api.crateApiShareInitScreenCapture();

List<SourceDescriptor> listShareSources() =>
    RustLib.instance.api.crateApiShareListShareSources();

Future<void> startShare({
  required String connectionId,
  required String sourceId,
  required ShareConfig config,
}) => RustLib.instance.api.crateApiShareStartShare(
  connectionId: connectionId,
  sourceId: sourceId,
  config: config,
);

Future<void> stopShare({required String connectionId}) =>
    RustLib.instance.api.crateApiShareStopShare(connectionId: connectionId);

class ShareConfig {
  final int fps;
  final int targetBitrateKbps;

  const ShareConfig({required this.fps, required this.targetBitrateKbps});

  @override
  int get hashCode => fps.hashCode ^ targetBitrateKbps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShareConfig &&
          runtimeType == other.runtimeType &&
          fps == other.fps &&
          targetBitrateKbps == other.targetBitrateKbps;
}

class SourceDescriptor {
  final String sourceId;
  final SourceKind kind;
  final String name;
  final int? width;
  final int? height;

  const SourceDescriptor({
    required this.sourceId,
    required this.kind,
    required this.name,
    this.width,
    this.height,
  });

  @override
  int get hashCode =>
      sourceId.hashCode ^
      kind.hashCode ^
      name.hashCode ^
      width.hashCode ^
      height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceDescriptor &&
          runtimeType == other.runtimeType &&
          sourceId == other.sourceId &&
          kind == other.kind &&
          name == other.name &&
          width == other.width &&
          height == other.height;
}

enum SourceKind { display, window }
