// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `as_ptr`, `current`, `install_copy_pixels_callback`, `new`, `publish_buffer`, `publish_owned_rgba`, `publish`, `rust_copy_pixels`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FrameStore`, `Slot`, `VideoTexture`

/// Returns the Flutter texture id registered by the runner. Returns 0 until
/// registration has completed; Dart should poll or retry briefly at startup.
PlatformInt64 getVideoTextureId() =>
    RustLib.instance.api.crateApiVideoTextureGetVideoTextureId();
