// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `claim`, `new`, `publish`, `release`, `slot_addr`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `VideoRing`

/// Free a slot previously delivered to Dart over the video stream.
///
/// MUST be called after Dart is done reading the slot's bytes — for example
/// after `ui.decodeImageFromPixels` has copied the pixels into a Skia
/// image. Failing to call this leaks the slot; once all four slots leak the
/// decoder will drop every subsequent frame.
void releaseVideoFrame({required int slot}) =>
    RustLib.instance.api.crateApiVideoRingReleaseVideoFrame(slot: slot);
