// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'webrtc.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `attach_data_channel`, `configure_ice_setting_engine`, `decode_incoming_track`, `ensure_data_channel`, `ensure_default_data_channels`, `ensure_local_audio_track`, `ensure_local_system_audio_track`, `get_api`, `get_session`, `new`, `normalize_sdp_kind`, `open_recv_stats_jsonl`, `parse_control_message`, `push_preview_frame`, `recv_stats_jsonl_path`, `should_gather_ice_ip`, `state_label`, `to_sdp_dto`, `to_webrtc_ice_server`, `wait_for_data_channel_open`, `wait_for_named_data_channel`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ParsedControlMessage`, `WebRtcSession`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<void> createSession({
  required String connectionId,
  required List<IceServerConfig> iceServers,
}) => RustLib.instance.api.crateApiWebrtcCreateSession(
  connectionId: connectionId,
  iceServers: iceServers,
);

Future<SessionDescriptionDto> createOffer({required String connectionId}) =>
    RustLib.instance.api.crateApiWebrtcCreateOffer(connectionId: connectionId);

Future<SessionDescriptionDto> createRestartOffer({
  required String connectionId,
}) => RustLib.instance.api.crateApiWebrtcCreateRestartOffer(
  connectionId: connectionId,
);

Future<SessionDescriptionDto> createAnswer({
  required String connectionId,
  required SessionDescriptionDto remoteOffer,
}) => RustLib.instance.api.crateApiWebrtcCreateAnswer(
  connectionId: connectionId,
  remoteOffer: remoteOffer,
);

Future<void> setRemoteAnswer({
  required String connectionId,
  required SessionDescriptionDto remoteAnswer,
}) => RustLib.instance.api.crateApiWebrtcSetRemoteAnswer(
  connectionId: connectionId,
  remoteAnswer: remoteAnswer,
);

Future<void> addIceCandidate({
  required String connectionId,
  required IceCandidateDto candidate,
}) => RustLib.instance.api.crateApiWebrtcAddIceCandidate(
  connectionId: connectionId,
  candidate: candidate,
);

Future<void> sendControlMessage({
  required String connectionId,
  required String message,
}) => RustLib.instance.api.crateApiWebrtcSendControlMessage(
  connectionId: connectionId,
  message: message,
);

Future<void> sendRenegotiationOffer({
  required String connectionId,
  required SessionDescriptionDto description,
}) => RustLib.instance.api.crateApiWebrtcSendRenegotiationOffer(
  connectionId: connectionId,
  description: description,
);

Future<void> sendRenegotiationAnswer({
  required String connectionId,
  required SessionDescriptionDto description,
}) => RustLib.instance.api.crateApiWebrtcSendRenegotiationAnswer(
  connectionId: connectionId,
  description: description,
);

Future<void> sendRenegotiationIce({
  required String connectionId,
  required IceCandidateDto candidate,
}) => RustLib.instance.api.crateApiWebrtcSendRenegotiationIce(
  connectionId: connectionId,
  candidate: candidate,
);

Future<void> sendFileTransferPrompt({required String connectionId}) => RustLib
    .instance
    .api
    .crateApiWebrtcSendFileTransferPrompt(connectionId: connectionId);

Future<void> sendSessionClosed({
  required String connectionId,
  required String id,
  String? reason,
}) => RustLib.instance.api.crateApiWebrtcSendSessionClosed(
  connectionId: connectionId,
  id: id,
  reason: reason,
);

Future<void> sendSessionClosedAck({
  required String connectionId,
  required String id,
}) => RustLib.instance.api.crateApiWebrtcSendSessionClosedAck(
  connectionId: connectionId,
  id: id,
);

Future<void> sendPing({required String connectionId, required String ts}) =>
    RustLib.instance.api.crateApiWebrtcSendPing(
      connectionId: connectionId,
      ts: ts,
    );

Future<void> sendPong({required String connectionId, String? ts}) => RustLib
    .instance
    .api
    .crateApiWebrtcSendPong(connectionId: connectionId, ts: ts);

Future<void> sendFileMessage({
  required String connectionId,
  required String message,
}) => RustLib.instance.api.crateApiWebrtcSendFileMessage(
  connectionId: connectionId,
  message: message,
);

Future<void> sendFileChunk({
  required String connectionId,
  required List<int> bytes,
}) => RustLib.instance.api.crateApiWebrtcSendFileChunk(
  connectionId: connectionId,
  bytes: bytes,
);

Future<BigInt> getFileBufferedAmount({required String connectionId}) => RustLib
    .instance
    .api
    .crateApiWebrtcGetFileBufferedAmount(connectionId: connectionId);

Future<void> setFileBufferedAmountLowThreshold({
  required String connectionId,
  required BigInt threshold,
}) => RustLib.instance.api.crateApiWebrtcSetFileBufferedAmountLowThreshold(
  connectionId: connectionId,
  threshold: threshold,
);

Future<void> createFileChannel({required String connectionId}) => RustLib
    .instance
    .api
    .crateApiWebrtcCreateFileChannel(connectionId: connectionId);

Future<void> waitForFileChannelReady({required String connectionId}) => RustLib
    .instance
    .api
    .crateApiWebrtcWaitForFileChannelReady(connectionId: connectionId);

Future<List<WebRtcEvent>> drainEvents({required String connectionId}) =>
    RustLib.instance.api.crateApiWebrtcDrainEvents(connectionId: connectionId);

Stream<WebRtcEvent> subscribeEventStream({required String connectionId}) =>
    RustLib.instance.api.crateApiWebrtcSubscribeEventStream(
      connectionId: connectionId,
    );

Stream<RawVideoFrame> subscribeVideoStream({required String connectionId}) =>
    RustLib.instance.api.crateApiWebrtcSubscribeVideoStream(
      connectionId: connectionId,
    );

Future<void> closeSession({required String connectionId}) =>
    RustLib.instance.api.crateApiWebrtcCloseSession(connectionId: connectionId);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<EventBus>>
abstract class EventBus implements RustOpaqueInterface {
  Future<void> pushEvent({required WebRtcEvent event});

  Future<void> pushVideoFrame({
    required PlatformInt64 addr,
    required int len,
    required int width,
    required int height,
    required int slot,
    required PlatformInt64 tsNs,
  });

  /// Variant that reports per-stage timing for the FRB hop. Returns
  /// `(mutex_lock_us, sink_add_us)`. When no sink is attached we release
  /// the slot immediately (we no longer buffer pixel data — the ring's
  /// slot lifetimes make that unworkable).
  Future<(BigInt, BigInt)> pushVideoFrameTimed({
    required PlatformInt64 addr,
    required int len,
    required int width,
    required int height,
    required int slot,
    required PlatformInt64 tsNs,
  });
}

class IceCandidateDto {
  final String candidate;
  final String? sdpMid;
  final int? sdpMlineIndex;

  const IceCandidateDto({
    required this.candidate,
    this.sdpMid,
    this.sdpMlineIndex,
  });

  @override
  int get hashCode =>
      candidate.hashCode ^ sdpMid.hashCode ^ sdpMlineIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IceCandidateDto &&
          runtimeType == other.runtimeType &&
          candidate == other.candidate &&
          sdpMid == other.sdpMid &&
          sdpMlineIndex == other.sdpMlineIndex;
}

class IceServerConfig {
  final List<String> urls;
  final String? username;
  final String? credential;

  const IceServerConfig({required this.urls, this.username, this.credential});

  @override
  int get hashCode => urls.hashCode ^ username.hashCode ^ credential.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IceServerConfig &&
          runtimeType == other.runtimeType &&
          urls == other.urls &&
          username == other.username &&
          credential == other.credential;
}

/// Descriptor for one decoded video frame. The pixel bytes live in the
/// shared `VIDEO_RING`; this struct carries only a pointer + length + slot
/// id across the FRB boundary. Dart wraps the pointer as a zero-copy
/// `Uint8List` view and MUST call `releaseVideoFrame(slot)` when done, or
/// the slot leaks. After all 4 slots leak the decoder drops every frame.
class RawVideoFrame {
  /// Raw pointer to the slot's bytes. Cast to i64 because Dart's `int` is
  /// 64-bit signed; the round-trip preserves the bit pattern.
  final PlatformInt64 addr;

  /// Bytes of decoded RGBA data (width * height * 4).
  final int len;
  final int width;
  final int height;

  /// Index into the ring buffer — pass back via `releaseVideoFrame`.
  final int slot;

  /// Wall-clock ns at the moment the decoder published the frame.
  final PlatformInt64 tsNs;

  const RawVideoFrame({
    required this.addr,
    required this.len,
    required this.width,
    required this.height,
    required this.slot,
    required this.tsNs,
  });

  @override
  int get hashCode =>
      addr.hashCode ^
      len.hashCode ^
      width.hashCode ^
      height.hashCode ^
      slot.hashCode ^
      tsNs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RawVideoFrame &&
          runtimeType == other.runtimeType &&
          addr == other.addr &&
          len == other.len &&
          width == other.width &&
          height == other.height &&
          slot == other.slot &&
          tsNs == other.tsNs;
}

class SessionDescriptionDto {
  final String kind;
  final String sdp;

  const SessionDescriptionDto({required this.kind, required this.sdp});

  @override
  int get hashCode => kind.hashCode ^ sdp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionDescriptionDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          sdp == other.sdp;
}

@freezed
sealed class WebRtcEvent with _$WebRtcEvent {
  const WebRtcEvent._();

  const factory WebRtcEvent.connectionStateChanged({required String state}) =
      WebRtcEvent_ConnectionStateChanged;
  const factory WebRtcEvent.dataChannelStateChanged({
    required String label,
    required String state,
  }) = WebRtcEvent_DataChannelStateChanged;
  const factory WebRtcEvent.localIceCandidate({
    required IceCandidateDto candidate,
  }) = WebRtcEvent_LocalIceCandidate;
  const factory WebRtcEvent.renegotiationOffer({
    required SessionDescriptionDto description,
  }) = WebRtcEvent_RenegotiationOffer;
  const factory WebRtcEvent.renegotiationAnswer({
    required SessionDescriptionDto description,
  }) = WebRtcEvent_RenegotiationAnswer;
  const factory WebRtcEvent.renegotiationIce({
    required IceCandidateDto candidate,
  }) = WebRtcEvent_RenegotiationIce;
  const factory WebRtcEvent.fileTransferRequested() =
      WebRtcEvent_FileTransferRequested;
  const factory WebRtcEvent.sessionClosed({String? id, String? reason}) =
      WebRtcEvent_SessionClosed;
  const factory WebRtcEvent.videoFrame({
    required Uint8List data,
    required int width,
    required int height,
  }) = WebRtcEvent_VideoFrame;
  const factory WebRtcEvent.sessionClosedAck({String? id}) =
      WebRtcEvent_SessionClosedAck;
  const factory WebRtcEvent.ping({String? ts}) = WebRtcEvent_Ping;
  const factory WebRtcEvent.pong({String? ts}) = WebRtcEvent_Pong;
  const factory WebRtcEvent.controlMessage({required String message}) =
      WebRtcEvent_ControlMessage;
  const factory WebRtcEvent.fileMessage({required String message}) =
      WebRtcEvent_FileMessage;
  const factory WebRtcEvent.fileChunk({required Uint8List bytes}) =
      WebRtcEvent_FileChunk;
  const factory WebRtcEvent.fileBufferedAmountLow() =
      WebRtcEvent_FileBufferedAmountLow;
}
