// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/audio.dart';
import 'api/client.dart';
import 'api/connection.dart';
import 'api/desktop_audio.dart';
import 'api/file_transfer.dart';
import 'api/input_inject.dart';
import 'api/models.dart';
import 'api/screen_capture.dart';
import 'api/simple.dart';
import 'api/transfer.dart';
import 'api/video_ring.dart';
import 'api/video_texture.dart';
import 'api/webrtc.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcRtcDataChannelPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcRtcPeerConnectionPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCPeerConnection;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_EventBusPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEventBus;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_PeerConnectionHandlePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ArcRtcDataChannel
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel(
    dynamic raw,
  );

  @protected
  ArcRtcPeerConnection
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCPeerConnection(
    dynamic raw,
  );

  @protected
  EventBus
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEventBus(
    dynamic raw,
  );

  @protected
  PeerConnectionHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    dynamic raw,
  );

  @protected
  PeerConnectionHandle
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    dynamic raw,
  );

  @protected
  EventBus
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEventBus(
    dynamic raw,
  );

  @protected
  PeerConnectionHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    dynamic raw,
  );

  @protected
  Map<String, ArcRtcDataChannel>
  dco_decode_Map_String_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel_None(
    dynamic raw,
  );

  @protected
  ArcRtcDataChannel
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel(
    dynamic raw,
  );

  @protected
  ArcRtcPeerConnection
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCPeerConnection(
    dynamic raw,
  );

  @protected
  EventBus
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEventBus(
    dynamic raw,
  );

  @protected
  PeerConnectionHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    dynamic raw,
  );

  @protected
  RustStreamSink<RawVideoFrame> dco_decode_StreamSink_raw_video_frame_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<WebRtcEvent> dco_decode_StreamSink_web_rtc_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AudioSourceDto dco_decode_audio_source_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CaptureConfigDto dco_decode_box_autoadd_capture_config_dto(dynamic raw);

  @protected
  IceCandidateDto dco_decode_box_autoadd_ice_candidate_dto(dynamic raw);

  @protected
  SessionDescriptionDto dco_decode_box_autoadd_session_description_dto(
    dynamic raw,
  );

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  WebRtcEvent dco_decode_box_autoadd_web_rtc_event(dynamic raw);

  @protected
  CaptureConfigDto dco_decode_capture_config_dto(dynamic raw);

  @protected
  CaptureSourceDto dco_decode_capture_source_dto(dynamic raw);

  @protected
  ConnectionInitLocalResult dco_decode_connection_init_local_result(
    dynamic raw,
  );

  @protected
  FileTransferStateDto dco_decode_file_transfer_state_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IceCandidateDto dco_decode_ice_candidate_dto(dynamic raw);

  @protected
  IceServerConfig dco_decode_ice_server_config(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AudioSourceDto> dco_decode_list_audio_source_dto(dynamic raw);

  @protected
  List<CaptureSourceDto> dco_decode_list_capture_source_dto(dynamic raw);

  @protected
  List<FileTransferStateDto> dco_decode_list_file_transfer_state_dto(
    dynamic raw,
  );

  @protected
  List<IceServerConfig> dco_decode_list_ice_server_config(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, ArcRtcDataChannel)>
  dco_decode_list_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_arc_rtc_data_channel(
    dynamic raw,
  );

  @protected
  List<WebRtcEvent> dco_decode_list_web_rtc_event(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  RawVideoFrame dco_decode_raw_video_frame(dynamic raw);

  @protected
  (String, ArcRtcDataChannel)
  dco_decode_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_arc_rtc_data_channel(
    dynamic raw,
  );

  @protected
  (BigInt, BigInt) dco_decode_record_u_64_u_64(dynamic raw);

  @protected
  SessionDescriptionDto dco_decode_session_description_dto(dynamic raw);

  @protected
  SignalingClientConfigDto dco_decode_signaling_client_config_dto(dynamic raw);

  @protected
  TransferStatusDto dco_decode_transfer_status_dto(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WebRtcEvent dco_decode_web_rtc_event(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ArcRtcDataChannel
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel(
    SseDeserializer deserializer,
  );

  @protected
  ArcRtcPeerConnection
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCPeerConnection(
    SseDeserializer deserializer,
  );

  @protected
  EventBus
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEventBus(
    SseDeserializer deserializer,
  );

  @protected
  PeerConnectionHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    SseDeserializer deserializer,
  );

  @protected
  PeerConnectionHandle
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    SseDeserializer deserializer,
  );

  @protected
  EventBus
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEventBus(
    SseDeserializer deserializer,
  );

  @protected
  PeerConnectionHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, ArcRtcDataChannel>
  sse_decode_Map_String_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel_None(
    SseDeserializer deserializer,
  );

  @protected
  ArcRtcDataChannel
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel(
    SseDeserializer deserializer,
  );

  @protected
  ArcRtcPeerConnection
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCPeerConnection(
    SseDeserializer deserializer,
  );

  @protected
  EventBus
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEventBus(
    SseDeserializer deserializer,
  );

  @protected
  PeerConnectionHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<RawVideoFrame> sse_decode_StreamSink_raw_video_frame_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<WebRtcEvent> sse_decode_StreamSink_web_rtc_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AudioSourceDto sse_decode_audio_source_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CaptureConfigDto sse_decode_box_autoadd_capture_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  IceCandidateDto sse_decode_box_autoadd_ice_candidate_dto(
    SseDeserializer deserializer,
  );

  @protected
  SessionDescriptionDto sse_decode_box_autoadd_session_description_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  WebRtcEvent sse_decode_box_autoadd_web_rtc_event(
    SseDeserializer deserializer,
  );

  @protected
  CaptureConfigDto sse_decode_capture_config_dto(SseDeserializer deserializer);

  @protected
  CaptureSourceDto sse_decode_capture_source_dto(SseDeserializer deserializer);

  @protected
  ConnectionInitLocalResult sse_decode_connection_init_local_result(
    SseDeserializer deserializer,
  );

  @protected
  FileTransferStateDto sse_decode_file_transfer_state_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IceCandidateDto sse_decode_ice_candidate_dto(SseDeserializer deserializer);

  @protected
  IceServerConfig sse_decode_ice_server_config(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AudioSourceDto> sse_decode_list_audio_source_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<CaptureSourceDto> sse_decode_list_capture_source_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<FileTransferStateDto> sse_decode_list_file_transfer_state_dto(
    SseDeserializer deserializer,
  );

  @protected
  List<IceServerConfig> sse_decode_list_ice_server_config(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, ArcRtcDataChannel)>
  sse_decode_list_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_arc_rtc_data_channel(
    SseDeserializer deserializer,
  );

  @protected
  List<WebRtcEvent> sse_decode_list_web_rtc_event(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  RawVideoFrame sse_decode_raw_video_frame(SseDeserializer deserializer);

  @protected
  (String, ArcRtcDataChannel)
  sse_decode_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_arc_rtc_data_channel(
    SseDeserializer deserializer,
  );

  @protected
  (BigInt, BigInt) sse_decode_record_u_64_u_64(SseDeserializer deserializer);

  @protected
  SessionDescriptionDto sse_decode_session_description_dto(
    SseDeserializer deserializer,
  );

  @protected
  SignalingClientConfigDto sse_decode_signaling_client_config_dto(
    SseDeserializer deserializer,
  );

  @protected
  TransferStatusDto sse_decode_transfer_status_dto(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WebRtcEvent sse_decode_web_rtc_event(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel(
    ArcRtcDataChannel self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCPeerConnection(
    ArcRtcPeerConnection self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEventBus(
    EventBus self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    PeerConnectionHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    PeerConnectionHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEventBus(
    EventBus self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    PeerConnectionHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Map_String_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel_None(
    Map<String, ArcRtcDataChannel> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel(
    ArcRtcDataChannel self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCPeerConnection(
    ArcRtcPeerConnection self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEventBus(
    EventBus self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    PeerConnectionHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_raw_video_frame_Sse(
    RustStreamSink<RawVideoFrame> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_web_rtc_event_Sse(
    RustStreamSink<WebRtcEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_audio_source_dto(
    AudioSourceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_capture_config_dto(
    CaptureConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ice_candidate_dto(
    IceCandidateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_session_description_dto(
    SessionDescriptionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_web_rtc_event(
    WebRtcEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_capture_config_dto(
    CaptureConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_capture_source_dto(
    CaptureSourceDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_connection_init_local_result(
    ConnectionInitLocalResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_file_transfer_state_dto(
    FileTransferStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_ice_candidate_dto(
    IceCandidateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ice_server_config(
    IceServerConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_audio_source_dto(
    List<AudioSourceDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_capture_source_dto(
    List<CaptureSourceDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_file_transfer_state_dto(
    List<FileTransferStateDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ice_server_config(
    List<IceServerConfig> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_list_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_arc_rtc_data_channel(
    List<(String, ArcRtcDataChannel)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_web_rtc_event(
    List<WebRtcEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_raw_video_frame(RawVideoFrame self, SseSerializer serializer);

  @protected
  void
  sse_encode_record_string_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_arc_rtc_data_channel(
    (String, ArcRtcDataChannel) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_64_u_64(
    (BigInt, BigInt) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_session_description_dto(
    SessionDescriptionDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_signaling_client_config_dto(
    SignalingClientConfigDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transfer_status_dto(
    TransferStatusDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_web_rtc_event(WebRtcEvent self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCPeerConnection(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCPeerConnection(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCPeerConnection(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCPeerConnection(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEventBus(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEventBus(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEventBus(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEventBus(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCDataChannel(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCPeerConnection(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcRTCPeerConnection(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEventBus(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEventBus(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPeerConnectionHandle(
    int ptr,
  );
}
