name: application
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  rust_lib_application:
    path: rust_builder
  flutter_rust_bridge: 2.12.0
  http: ^1.2.0
  qr_flutter: ^4.1.0
  share_plus: ^12.0.1
  logging: ^1.3.0
  web_socket_channel: ^3.0.3
  path_provider: ^2.1.5
  file_picker: ^10.3.8
  crypto: ^3.0.7
  file_selector: ^1.1.0
  desktop_drop: ^0.7.0
  shared_preferences: ^2.2.2
  freezed_annotation: ^2.4.4
  lucide_icons_flutter: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  fake_async: ^1.3.3
  flutter_lints: ^6.0.0
  freezed: ^2.5.8
  build_runner: ^2.4.12
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - shaders/

  fonts:
    - family: Geist Mono
      fonts:
        - asset: assets/fonts/GeistMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/GeistMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/GeistMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/GeistMono-Bold.ttf
          weight: 700
    - family: Space Grotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
          weight: 700
